// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8LDhdql6s--v9HrGXEjT9Kxmh3DGS-Dk',
    appId: '1:682220574902:android:1fcaa014417ae8b9d1ee17',
    messagingSenderId: '682220574902',
    projectId: 'taskhub-2012d',
    storageBucket: 'taskhub-2012d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrElk1gHHXfJpkNj0MXP5T7GFe1XP_EVI',
    appId: '1:682220574902:ios:d59318c37ada366ad1ee17',
    messagingSenderId: '682220574902',
    projectId: 'taskhub-2012d',
    storageBucket: 'taskhub-2012d.appspot.com',
    androidClientId: '682220574902-90hpva6ln2uc839fah0ubugm8ergldlg.apps.googleusercontent.com',
    iosClientId: '682220574902-4pvuptmnh2p2gt28444rpmp3oeltq4c2.apps.googleusercontent.com',
    iosBundleId: 'com.artempetrushenko.taskhub',
  );
}
